{
 "title": "Spring Sandbox Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "Memory Used Bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Gateway requests (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_requests_seconds_max", "legendFormat": "Max Requests" },
    {
     "expr": "rate(gateway_requests_seconds_sum[1m])",
     "legendFormat": "Sum Requests"
    },
    {
     "expr": "rate(gateway_requests_seconds_count[1m])",
     "legendFormat": "Requests Count"
    }
   ]
  }
 ]
}